name: Build Mac OS Dolphin

on: [push, workflow_dispatch]

jobs:
  build:
    name: "${{ matrix.runs-on }} • ${{ matrix.arch }}"
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - runs-on: macos-15
            arch: arm64
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Install Qt
        run: |
          brew update
          brew tap-new workflow/homebrew-custom
          curl -o /tmp/qt.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/63d2e0609cdc80b0b96472721f9adf55bd74696b/Formula/q/qt.rb
          mv /tmp/qt.rb $(brew --repo workflow/homebrew-custom)/Formula/qt.rb
          brew install workflow/custom/qt
          # curl -o /tmp/qt.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/63d2e0609cdc80b0b96472721f9adf55bd74696b/Formula/q/qt.rb
          # HOMEBREW_NO_AUTO_UPDATE=1 brew install --formula /tmp/qt.rb

      - name: Configure Dolphin
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DENABLE_AUTOUPDATE=OFF
          tar -czf dolphin_mac.tar.gz Binaries/

      - name: Try Building Dolphin
        run: |
          cd build
          make -j$(sysctl -n hw.logicalcpu)
        continue-on-error: true

      - name: Try Building Dolphin Again
        run: |
          cd build
          make -j$(sysctl -n hw.logicalcpu)
          tar -czf dolphin_mac.tar.gz Binaries/

      - name: Upload Build
        uses: actions/upload-artifact@v6
        with:
          name: DolphinMac-${{ matrix.arch }}
          path: build/dolphin_mac.tar.gz