name: Build Mac OS Wheel

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Qt
        run: |
          brew update
          brew install qt

      - name: Build Dolphin
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DSKIP_POSTPROCESS_BUNDLE=ON
          make -j$(sysctl -n hw.logicalcpu)
          tar -czf dolphin_mac.tar.gz Binaries/

      - name: Upload Dolphin Mac
        uses: actions/upload-artifact@v4
        with:
          name: DolphinMac
          path: Binaries/dolphin_mac.tar.gz