name: Build Win Dolphin

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build Dolphin
        run: |
          cmake -Bbuild . -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -- /m
          ls

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: DolphinWin
          path: Binary